[package]
name = "Obolus"
version = "0.0.16"
edition = "2021"

[dependencies]
tui = "0.19"
crossterm = "0.26"
serde_json = "1.0"
plotters = "0.3"  # For graphs
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }

